Traceback (most recent call last):
  File "D:\NCTU_Course\Indenpent Study\Tracknet V2\VideroFrame\web\cgi-bin\auto_main.py", line 73, in <module>
    auto_segmentation.run(segmentation_input, segmentation_output)
  File "D:\NCTU_Course\Indenpent Study\Tracknet V2\VideroFrame\web\cgi-bin\auto_segmentation.py", line 697, in run
    readData(segmentation_input)
  File "D:\NCTU_Course\Indenpent Study\Tracknet V2\VideroFrame\web\cgi-bin\auto_segmentation.py", line 16, in readData
    df = pd.read_csv(segmentation_input)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'./preprocessing/Data/TrainTest/Badminton_label_1.csv' does not exist
